name: Deploy Flask Backend to Cloud Run

on:
  push:
    paths:
      - "cap-backend/**"
      - ".github/workflows/deploy-backend.yml"
    branches:
      - main

env:
  PROJECT_ID: capgemini-project-464807
  REGION: us-central1
  SERVICE_NAME: flask-app
  REPO_NAME: flask-repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 -t us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$SERVICE_NAME:latest ./backend

      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$SERVICE_NAME:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$SERVICE_NAME:latest \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated
